# 这个文件启动：docker-compose -p whattoeat-prod up -d --build

services:
  backend:
    build: ./packages/backend
    container_name: backend-eat
    environment:
      NODE_ENV: production
    # depends_on:
    #   - db

  frontend:
    build: ./packages/frontend
    container_name: frontend-eat
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:alpine
    container_name: nginx-eat
    ports:
      - '8000:8000'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
