services:
  db:
    image: mysql:8.0
    container_name: mysql-eat
    restart: always
    environment:
      # username: root, password: rootpass
      MYSQL_ROOT_PASSWORD: rootpass
      # username: ming, password: 123
      MYSQL_USER: ming
      MYSQL_PASSWORD: 123

      MYSQL_DATABASE: testdb
    ports:
      - '3307:3306' #左边是我本地电脑的端口，右边永远是容器的3306
    volumes:
      - mysql_data:/var/lib/mysql-eat

  adminer:
    image: adminer
    container_name: adminer-eat
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

  backend:
    build: ./packages/backend
    container_name: backend-eat
    environment:
      NODE_ENV: docker
    depends_on:
      - db

  frontend:
    build: ./packages/frontend
    container_name: frontend-eat
    environment:
      NODE_ENV: development

  nginx:
    image: nginx:alpine
    container_name: nginx-eat
    ports:
      - '8000:8000'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
