# 这个文件在 npm run dev 命令下用到

db:
  mysql:
    host: 127.0.0.1
    name: testdb
    port: 3307 # 这里的port要和 docker-compose.yml里映射的我电脑port一致
    sync: true
    type: mysql
    username: root
    password: rootpass
log:
  level: info
  on: true
