# è¿™ä¸ªæ–‡ä»¶åœ¨ docker-compose -p whattoeat up -d --build å‘½ä»¤ä¸‹ç”¨åˆ°

db:
  mysql:
    host: db # ğŸ‘ˆ service name
    name: testdb
    port: 3306 # ğŸ‘ˆ containerå†…éƒ¨ç«¯å£
    sync: true
    type: mysql
    username: root
    password: rootpass
log:
  level: info
  on: true
