db:
  mysql:
    host: defaultHost
    name: mysql-default1
    port: 0000
    sync: false
    type: mysql
    username: defaultName
    password: defaultPassword

# secrets:
#   jwtSecret: ming_secret
